#!/usr/bin/env python3
"""Generate the forwarding stubs (stubs.S) and export list (opengl32.def) for the shim.

Every export in opengl32.exports gets a stub that jumps through real_fns[i], which hwgl.c fills
from the system opengl32.dll at load time. Exports listed in OVERRIDES jump to our own
implementation in hwgl.c instead.
"""
import sys
from pathlib import Path

# export name -> stdcall-decorated C symbol in hwgl.c
OVERRIDES = {
    "wglCreateContext": "_hw_wglCreateContext@4",
    "wglGetProcAddress": "_hw_wglGetProcAddress@4",
    "glGetString": "_hw_glGetString@4",
}


def main():
    here = Path(__file__).parent
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else here
    names = [n.strip() for n in (here / "opengl32.exports").read_text().split() if n.strip()]

    s = ["# Generated by gen_stubs.py - do not edit.", ".text"]
    for i, name in enumerate(names):
        s.append(f".globl _stub_{name}")
        s.append(f"_stub_{name}:")
        s.append(f"    jmp {OVERRIDES[name]}" if name in OVERRIDES else f"    jmp *_real_fns+{4 * i}")
    s += [".data", ".globl _real_fns", ".p2align 2", "_real_fns:", f"    .fill {len(names)}, 4, 0",
          ".section .rdata", ".globl _export_names", ".p2align 2", "_export_names:"]
    s += [f"    .long .Lname{i}" for i in range(len(names))]
    s += [f".Lname{i}: .asciz \"{name}\"" for i, name in enumerate(names)]
    s += [".globl _export_count", ".p2align 2", f"_export_count: .long {len(names)}", ""]
    (out / "stubs.S").write_text("\n".join(s))

    d = ["LIBRARY opengl32.dll", "EXPORTS"] + [f"    {name}=stub_{name}" for name in names]
    (out / "opengl32.def").write_text("\n".join(d) + "\n")


if __name__ == "__main__":
    main()
